[package]
name = "dungeon-app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = "0.16"
crossterm = "0.29.0"
ratatui = "0.30.2"
dungeon-core = { path = "dungeon-core" }
dungeon-action = { path = "dungeon-action" }
dungeon-world = { path = "dungeon-world" }
dungeon-render = { path = "dungeon-render" }
core = { path = "core" }
utils = { path = "utils" }
sys = { path = "sys" }
tui = { path = "tui" }
bincode = "1.3"
log = "0.4"

[workspace]
members = [
    "dungeon-core",
    "dungeon-action",
    "dungeon-world",
    "dungeon-render",
    "terrain-forge",
    "core",
    "render-api",
    "utils",
    "sys",
    "tui",
]

[workspace.dependencies]
log = "0.4"
bevy_ecs = "0.16"
render-api = { path = "render-api" }